# Generated by Django 4.2.2 on 2023-12-24 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_course_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='url',
            field=models.CharField(default='http://127.0.0.1:8000/', max_length=90),
        ),
    ]
