# Generated by Django 4.2.2 on 2023-12-24 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_course_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='image',
            field=models.ImageField(default='course_image.png', upload_to=''),
        ),
    ]
