# Generated by Django 4.2.2 on 2023-12-24 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_course_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='courses',
            field=models.ManyToManyField(blank=True, to='home.course'),
        ),
    ]
