# Generated by Django 4.2.2 on 2023-12-26 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_inventory_courses'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='category',
            field=models.CharField(choices=[('M', 'Math'), ('L', 'Languages'), ('N', 'Natural Science'), ('H', 'Human Science')], default='A', max_length=1),
        ),
    ]
