# Generated by Django 4.2.2 on 2024-01-06 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_historic_date_matriceshistoric'),
    ]

