# Generated by Django 4.2.2 on 2024-01-06 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_historic_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='matriceshistoric',
            old_name='number_colunms',
            new_name='number_colunms_a',
        ),
        migrations.RenameField(
            model_name='matriceshistoric',
            old_name='number_rows',
            new_name='number_rows_a',
        ),
      
 
        migrations.AddField(
            model_name='matriceshistoric',
            name='determinant',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='matriceshistoric',
            name='number_colunms_b',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='matriceshistoric',
            name='number_rows_b',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
