# Generated by Django 4.2.2 on 2024-01-06 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_rename_number_colunms_matriceshistoric_number_colunms_a_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='matriceshistoric',
            name='matrix',
        ),
        migrations.AddField(
            model_name='matriceshistoric',
            name='matrix_a',
            field=models.TextField(default='[]'),
        ),
        migrations.AddField(
            model_name='matriceshistoric',
            name='matrix_b',
            field=models.TextField(blank=True, null=True),
        ),
    ]
