# Generated by Django 4.2.2 on 2024-01-07 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_remove_matriceshistoric_matrix_historic_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='matriceshistoric',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
