# Generated by Django 4.2.2 on 2024-01-07 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_historic_date_matriceshistoric_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matriceshistoric',
            name='determinant',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
