# Generated by Django 4.2.2 on 2024-01-09 22:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_historic_date_alter_matriceshistoric_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historic',
            name='type_app',
            field=models.CharField(choices=[('pa', 'PA'), ('pg', 'PG'), ('ps', 'Pascal'), ('bi', "Newton's Binomial"), ('fc', 'Function Calculator')], max_length=2),
        ),
        migrations.CreateModel(
            name='HistoricFuction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('function', models.TextField(default='x')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
