# Generated by Django 4.2.2 on 2024-01-09 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_historic_date_alter_historic_type_app_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='HistoricFuction',
            new_name='HistoricFunction',
        ),
        
        
    ]
