# Generated by Django 4.2.2 on 2024-01-09 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_rename_historicfuction_historicfunction_and_more'),
    ]

  
    
