# Generated by Django 4.2.2 on 2024-01-09 23:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_historic_date'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='HistoricFunction',
            new_name='FunctionHistoric',
        ),
    ]
