# Generated by Django 4.2.2 on 2024-01-13 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_rename_historicfunction_functionhistoric'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='category',
            field=models.CharField(choices=[('M', 'Matemática'), ('L', 'Linguagens'), ('N', 'Ciências da Natureza'), ('H', 'Ciências Humanas')], default='A', max_length=1),
        ),
    ]
