# Generated by Django 4.2.2 on 2024-01-13 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_historic_date_alter_course_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historic',
            name='type_app',
            field=models.CharField(choices=[('pa', 'PA'), ('pg', 'PG'), ('ps', 'Pascal'), ('bi', 'Binômio de Newton'), ('fc', 'Calculadora de Função')], max_length=2),
        ),
    ]
