# Generated by Django 4.2.2 on 2024-01-14 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0022_historic_date_alter_historic_type_app'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historic',
            name='type_app',
            field=models.CharField(choices=[('pa', 'PA'), ('pg', 'PG'), ('ps', 'Pascal'), ('bi', 'Binômio de Newton')], max_length=2),
        ),
    ]
